class Armor:
  def __init__(self, name, tier, base_thresholds, score, feature):
    self.name = name
    self.tier = tier
    self.base_thresholds = base_thresholds
    self.score = score
    self.feature = feature
  def __str__(self):
    return self.name

ARMOR = [
  Armor("Gambeson Armor", "1", "5 / 11", "3", "Flexible: +1 to Evasion"),
  Armor("Leather Armor", "1", "6 / 13", "3", ":"),
  Armor("Chainmail Armor", "1", "7 / 15", "4", "Heavy: -1 to Evasion"),
  Armor("Full Plate Armor", "1", "8 / 17", "4", "Very Heavy: -2 to Evasion; -1 to Agility"),
  Armor("Mage Robes", "1", "4/10", "2", "Enchanted: Gain a bonus to your damage thresholds equal to your spellcast trait."),
  Armor("Brigandine Armor", "1", "6/12", "3", "Lined: Mark a Stress to negate Minor damage."),
  Armor("Scale Mail Armor", "1", "7/14", "3", "Cumbersome: -1 to Finesse"),
  Armor("Banded Armor", "1", "8/16", "4", "Bulky: -1 to Evasion; when you take Severe damage, you must mark a Stress."),
  Armor("Improved Gambeson Armor", "2", "7 / 16", "4", "Flexible: +1 to Evasion"),
  Armor("Improved Leather Armor", "2", "9 / 20", "4", ":"),
  Armor("Improved Chainmail Armor", "2", "11 / 24", "5", "Heavy: -1 to Evasion"),
  Armor("Improved Full Plate Armor", "2", "13 / 28", "5", "Very Heavy: -2 to Evasion; -1 to Agility"),
  Armor("Improved Mage Robes", "2", "6/15", "3", "Enchanted: Gain a bonus to your damage thresholds equal to your spellcast trait."),
  Armor("Improved Brigandine Armor", "2", "9/19", "4", "Lined: Mark a Stress to negate Minor damage."),
  Armor("Improved Scale Mail Armor", "2", "11/23", "4", "Cumbersome: -1 to Finesse"),
  Armor("Improved Banded Armor", "2", "13/27", "5", "Bulky: -1 to Evasion; when you take Severe damage, you must mark a Stress."),
  Armor("Elundrian Chain Armor", "2", "9 / 21", "4", "Warded: You reduce incoming magic damage by your Armor Score before applying it to your damage thresholds."),
  Armor("Harrowbone Armor", "2", "9 / 21", "4", "Resilient: Before you mark your last Armor Slot, roll a d6. On a result of 6, reduce the severity by one threshold without marking an Armor Slot."),
  Armor("Irontree Breastplate Armor", "2", "9 / 20", "4", "Reinforced: When you mark your last Armor Slot, increase your damage thresholds by +2 until you clear at least 1 Armor Slot."),
  Armor("Runetan Floating Armor", "2", "9 / 20", "4", "Shifting: When you are targeted for an attack, you can mark an Armor Slot to give the attack roll against you disadvantage."),
  Armor("Tyris Soft Armor", "2", "8 / 18", "5", "Quiet: You gain a +2 bonus to rolls you make to move silently."),
  Armor("Rosewild Armor", "2", "11 / 23", "5", "Hopeful: When you would spend a Hope, you can mark an Armor Slot instead."),
  Armor("Enchanter's Robes", "2", "9/20", "4", "Mnemonic: Once per scene, you can recall a domain card from your vault without paying its Recall Cost."),
  Armor("Hawkguards Mantle", "2", "9/20", "4", "Gliding: You can glide up to Far range and are immune to damage from falling."),
  Armor("Spidersilk Tunic", "2", "9/20", "4", "Wall-Crawling: +1 to Evasion; you can walk on walls as easily as on the ground."),
  Armor("Stormthread Habit", "2", "9/20", "4", "Absorbing: Once per scene when you take magic damage, you can clear an Armor Slot."),
  Armor("Wyrdwood Splint Armor", "2", "10/21", "5", "Quick-Striding: You can't be Restrained and can move up to Far range as part of an action roll."),
  Armor("Trollhide Cuirass", "2", "11/23", "5", "Self-Healing: When you take a rest, clear an Armor slot."),
  Armor("Glided Sunplate", "2", "12/26", "5", "REsplendent: Once per scene when you spend Hope, you can clear an Armor Slot."),
  Armor("Advanced Gambeson Armor", "3", "9 / 23", "5", "Flexible: +1 to Evasion"),
  Armor("Advanced Leather Armor", "3", "11 / 27", "5", ":"),
  Armor("Advanced Chainmail Armor", "3", "13 / 31", "6", "Heavy: -1 to Evasion"),
  Armor("Advanced Full Plate Armor", "3", "15 / 35", "6", "Very Heavy: -2 to Evasion; -1 to Agility"),
  Armor("Improved Mage Robes", "3", "8/22", "4", "Enchanted: Gain a bonus to your damage thresholds equal to your spellcast trait."),
  Armor("Improved Brigandine Armor", "3", "11/26", "5", "Lined: Mark a Stress to negate Minor damage."),
  Armor("Improved Scale Mail Armor", "3", "13/30", "5", "Cumbersome: -1 to Finesse"),
  Armor("Improved Banded Armor", "3", "15/34", "6", "Bulky: -1 to Evasion; when you take Severe damage, you must mark a Stress."),
  Armor("Bellamie Fine Armor", "3", "11 / 27", "5", "Gilded: +1 to Presence"),
  Armor("Dragonscale Armor", "3", "11 / 27", "5", "Impenetrable: Once per short rest, when you would mark your last Hit Point, you can instead mark a Stress."),
  Armor("Spiked Plate Armor", "3", "10 / 25", "5", "Sharp: On a successful attack against a target within Melee range, add a d4 to the damage roll."),
  Armor("Bladefare Armor", "3", "16 / 39", "6", "Physical: You can't mark an Armor Slot to reduce magic damage."),
  Armor("Monett's Cloak", "3", "16 / 39", "6", "Magic: You can't mark an Armor Slot to reduce physical damage."),
  Armor("Runes of Fortification", "3", "17 / 43", "6", "Painful: Each time you mark an Armor Slot, you must mark a Stress."),
  Armor("Granminister's Finery", "3", "11/27", "2", "Magnificent: Gain a bonus to your Armor Score equal to your Presence."),
  Armor("Astral RAiment", "3", "11/27", "5", "Stellar: Mark a Stress to gain advantage on a Spellcast Roll."),
  Armor("Cloverweave Cloak", "3", "11/27", "5", "Fortune-Favored: Once per scene, you can change a failure with Hope into a success with Fear."),
  Armor("Skywarden's Lamellar", "3", "11/27", "5", "Vigilant: +2 to Evasion"),
  Armor("Bloodstone Plate Armor", "3", "13/35", "6", "Bloodthirsty: When you critically succeed on a weapon attack within Melee range, clear a Hit Point."),
  Armor("Deep-Forged Coral Armor", "3", "13/35", "6", "Aquatic: You can breathe underwater and gain advantage on Agility Rolls while submerged."),
  Armor("Legendary Gambeson Armor", "4", "11 / 32", "6", "Flexible: +1 to Evasion"),
  Armor("Legendary Leather Armor", "4", "13 / 36", "6", ":"),
  Armor("Legendary Chainmail Armor", "4", "15 / 40", "7", "Heavy: -1 to Evasion"),
  Armor("Legendary Full Plate Armor", "4", "17 / 44", "7", "Very Heavy: -2 to Evasion; -1 to Agility"),
  Armor("Legendary Mage Robes", "4", "10/31", "5", "Enchanted: Gain a bonus to your damage thresholds equal to your spellcast trait."),
  Armor("Legendary Brigandine Armor", "4", "13/35", "6", "Lined: Mark a Stress to negate Minor damage."),
  Armor("Legendary Scale Mail Armor", "4", "15/39", "6", "Cumbersome: -1 to Finesse"),
  Armor("Legendary Banded Armor", "4", "17/43", "7", "Bulky: -1 to Evasion; when you take Severe damage, you must mark a Stress."),
  Armor("Dunamis Silkchain", "4", "13 / 36", "7", "Timeslowing: Mark an Armor Slot to roll a d4 and add its result as a bonus to your Evasion against an incoming attack."),
  Armor("Channeling Armor", "4", "13 / 36", "5", "Channeling: +1 to Spellcast Rolls"),
  Armor("Emberwoven Armor", "4", "13 / 36", "6", "Burning: When an adversary attacks you within Melee range, they mark a Stress."),
  Armor("Full Fortified Armor", "4", "15 / 40", "4", "Fortified: When you mark an Armor Slot, you reduce the severity of an attack by two thresholds instead of one."),
  Armor("Veritas Opal Armor", "4", "13 / 36", "6", "Truthseeking: This armor glows when another creature within Close range tells a lie."),
  Armor("Savior Chainmail", "4", "18 / 48", "8", "Difficult: -1 to all character traits and Evasion"),
  Armor("Darkweave Shroud", "4", "13/36", "5", "Ghostwalker: Once per rest, mark a Stress to move up to Close range through solid objects."),
  Armor("Godbound Laminar", "4", "13/36", "6", "Divine: When you mark an Armor Slot, gain a Hope"),
  Armor("Circle-Forged Dreadplate", "4", "14/38", "6", "Accursed: When you mark any number of Hit Points from an attack, roll a d4. On a result of 4, the attacker must mark an equal number of Stress."),
  Armor("Rune-Forged Exosuit", "4", "12/39", "7", "Attuned: The maximum number of domain cards in your loadout is reduced by one, but you gain a bonus to your damage thresholds equal to your tier."),
  Armor("Hallowed Heroplate", "4", "13/35", "7", "Blessed: Once per long rest, you can spend any number of Hope before you make the Risk It All death move. You gain a bonus to the result of your Hope die equal to the number of Hope Spent."),
  Armor("Resonant Harness", "4", "15/40", "7", "Vitreous: When you would take Severe or greater damage, you can mark 2 Armor Slots to negate that damage. If you do, you gain a -5 penalty to your damage thresholds until you choose to repair your armor as a downtime move."),
]
