class Weapon:
  def __init__(self, name, weapon_type, damage_type, trait, range, damage, burden, feature, tier):
    self.name = name
    self.weapon_type = weapon_type
    self.damage_type = damage_type
    self.trait = trait
    self.range = range
    self.damage = damage
    self.burden = burden
    self.feature = feature
    self.tier = tier

  def __str__(self):
    return self.name

WEAPONS = [
  Weapon("Broadsword", "Primary", "Physical", "Agility", "Melee", "d8 phy", "One-Handed", "Reliable: +1 to attack rolls", 1),
  Weapon("Longsword", "Primary", "Physical", "Agility", "Melee", "d10+3 phy", "Two-Handed", ":", 1),
  Weapon("Battleaxe", "Primary", "Physical", "Strength", "Melee", "d10+3 phy", "Two-Handed", ":", 1),
  Weapon("Greatsword", "Primary", "Physical", "Strength", "Melee", "d10+3 phy", "Two-Handed", "Massive: -1 to Evasion; on a successful attack, roll an additional damage die and discard the lowest result.", 1),
  Weapon("Mace", "Primary", "Physical", "Strength", "Melee", "d8+1 phy", "One-Handed", ":", 1),
  Weapon("Warhammer", "Primary", "Physical", "Strength", "Melee", "d12+3 phy", "Two-Handed", "Heavy: -1 to Evasion", 1),
  Weapon("Dagger", "Primary", "Physical", "Finesse", "Melee", "d8+1 phy", "One-Handed", ":", 1),
  Weapon("Quarterstaff", "Primary", "Physical", "Instinct", "Melee", "d10+3 phy", "Two-Handed", ":", 1),
  Weapon("Cutlass", "Primary", "Physical", "Presence", "Melee", "d8+1 phy", "One-Handed", ":", 1),
  Weapon("Rapier", "Primary", "Physical", "Presence", "Melee", "d8 phy", "One-Handed", "Quick: When you make an attack, you can mark a Stress to target another creature within range.", 1),
  Weapon("Halberd", "Primary", "Physical", "Strength", "Very Close", "d10+2 phy", "Two-Handed", "Cumbersome: -1 to Finesse", 1),
  Weapon("Spear", "Primary", "Physical", "Finesse", "Very Close", "d8+3 phy", "Two-Handed", ": -1 to Finesse", 1),
  Weapon("Shortbow", "Primary", "Physical", "Agility", "Far", "d6+3 phy", "Two-Handed", ":", 1),
  Weapon("Crossbow", "Primary", "Physical", "Finesse", "Far", "d6+1 phy", "One-Handed", ":", 1),
  Weapon("Longbow", "Primary", "Physical", "Agility", "Very Far", "d8+3 phy", "Two-Handed", "Cumbersome: -1 to Finesse", 1),
  Weapon("Arcane Gauntlets", "Primary", "Magical", "Strength", "Melee", "d10+3 mag", "Two-Handed", ":", 1),
  Weapon("Hallowed Axe", "Primary", "Magical", "Strength", "Melee", "d8+1 mag", "One-Handed", ":", 1),
  Weapon("Glowing Rings", "Primary", "Magical", "Agility", "Very Close", "d10+2 mag", "Two-Handed", ":", 1),
  Weapon("Hand Runes", "Primary", "Magical", "Instinct", "Very Close", "d10 mag", "One-Handed", ":", 1),
  Weapon("Returning Blade", "Primary", "Magical", "Finesse", "Close", "d8 mag", "One-Handed", "Returning: When this weapon is thrown within its range, it appears in your hand immediately after the attack.", 1),
  Weapon("Shortstaff", "Primary", "Magical", "Instinct", "Close", "d8+1 mag", "One-Handed", ":", 1),
  Weapon("Dualstaff", "Primary", "Magical", "Instinct", "Far", "d6+3 mag", "Two-Handed", ":", 1),
  Weapon("Scepter", "Primary", "Magical", "Presence", "Far", "d6 mag", "Two-Handed", "Versatile: This weapon can also be used with these statistics—Presence, Melee, d8.", 1),
  Weapon("Wand", "Primary", "Magical", "Knowledge", "Far", "d6+1 mag", "One-Handed", ":", 1),
  Weapon("Greatstaff", "Primary", "Magical", "Knowledge", "Very Far", "d6 mag", "Two-Handed", "Powerful: On a successful attack, roll an additional damage die and discard the lowest result.", 1),
  Weapon("Shortsword", "Secondary", "Physical", "Agility", "Melee", "d8 phy", "One-Handed", "Paired: +2 to primary weapon damage to targets within Melee range", 1),
  Weapon("Round Shield", "Secondary", "Physical", "Strength", "Melee", "d4 phy", "One-Handed", "Protective: +1 to Armor Score", 1),
  Weapon("Tower Shield", "Secondary", "Physical", "Strength", "Melee", "d6 phy", "One-Handed", "Barrier: +2 to Armor Score; -1 to Evasion", 1),
  Weapon("Small Dagger", "Secondary", "Physical", "Finesse", "Melee", "d8 phy", "One-Handed", "Paired: +2 to primary weapon damage to targets within Melee range", 1),
  Weapon("Whip", "Secondary", "Physical", "Presence", "Very Close", "d6 phy", "One-Handed", "Startling: Mark a Stress to crack the whip and force all adversaries within Melee range back to Close range.", 1),
  Weapon("Grappler", "Secondary", "Physical", "Finesse", "Close", "d6 phy", "One-Handed", "Hooked: On a successful attack, you can pull the target into Melee range.", 1),
  Weapon("Hand Crossbow", "Secondary", "Physical", "Finesse", "Far", "d6+1 phy", "One-Handed", ":", 1),
  Weapon("Improved Broadsword", "Primary", "Physical", "Agility", "Melee", "d8+3 phy", "One-Handed", "Reliable: +1 to attack rolls", 2),
  Weapon("Improved Longsword", "Primary", "Physical", "Agility", "Melee", "d10+6 phy", "Two-Handed", ":", 2),
  Weapon("Improved Battleaxe", "Primary", "Physical", "Strength", "Melee", "d10+6 phy", "Two-Handed", ":", 2),
  Weapon("Improved Greatsword", "Primary", "Physical", "Strength", "Melee", "d10+6 phy", "Two-Handed", "Massive: -1 to Evasion; on a successful attack, roll an additional damage die and discard the lowest result.", 2),
  Weapon("Improved Mace", "Primary", "Physical", "Strength", "Melee", "d8+4 phy", "One-Handed", ":", 2),
  Weapon("Improved Warhammer", "Primary", "Physical", "Strength", "Melee", "d12+6 phy", "Two-Handed", "Heavy: -1 to Evasion", 2),
  Weapon("Improved Dagger", "Primary", "Physical", "Finesse", "Melee", "d8+4 phy", "One-Handed", ":", 2),
  Weapon("Improved Quarterstaff", "Primary", "Physical", "Instinct", "Melee", "d10+6 phy", "Two-Handed", ":", 2),
  Weapon("Improved Cutlass", "Primary", "Physical", "Presence", "Melee", "d8+4 phy", "One-Handed", ":", 2),
  Weapon("Improved Rapier", "Primary", "Physical", "Presence", "Melee", "d8+3 phy", "One-Handed", "Quick: When you make an attack, you can mark a Stress to target another creature within range.", 2),
  Weapon("Improved Halberd", "Primary", "Physical", "Strength", "Very Close", "d10+5 phy", "Two-Handed", "Cumbersome: -1 to Finesse", 2),
  Weapon("Improved Spear", "Primary", "Physical", "Finesse", "Very Close", "d8+6 phy", "Two-Handed", ": -1 to Finesse", 2),
  Weapon("Improved Shortbow", "Primary", "Physical", "Agility", "Far", "d6+6 phy", "Two-Handed", ":", 2),
  Weapon("Improved Crossbow", "Primary", "Physical", "Finesse", "Far", "d6+4 phy", "One-Handed", ":", 2),
  Weapon("Improved Longbow", "Primary", "Physical", "Agility", "Very Far", "d8+6 phy", "Two-Handed", "Cumbersome: -1 to Finesse", 2),
  Weapon("Gilded Falchion", "Primary", "Physical", "Strength", "Melee", "d10+4 phy", "One-Handed", "Powerful: On a successful attack, roll an additional damage die and discard the lowest result.", 2),
  Weapon("Knuckle Blades", "Primary", "Physical", "Strength", "Melee", "d10+6 phy", "One-Handed", "Brutal: When you roll the maximum value on a damage die, roll an additional damage die.", 2),
  Weapon("Urok Broadsword", "Primary", "Physical", "Finesse", "Melee", "d8+3 phy", "One-Handed", "Deadly: When you deal Severe damage, the target must mark an additional HP.", 2),
  Weapon("Bladed Whip", "Primary", "Physical", "Agility", "Very Close", "d8+3 phy", "One-Handed", "Quick: When you make an attack, you can mark a Stress to target another creature within range.", 2),
  Weapon("Steelforged Halberd", "Primary", "Physical", "Strength", "Very Close", "d8+4 phy", "Two-Handed", "Scary: On a successful attack, the target must mark a Stress.", 2),
  Weapon("War Scythe", "Primary", "Physical", "Finesse", "Very Close", "d8+5 phy", "Two-Handed", "Reliable: +1 to attack rolls", 2),
  Weapon("Blunderbuss", "Primary", "Physical", "Finesse", "Close", "d8+6 phy", "Two-Handed", "Reloading: After you make an attack, roll a d6. On a result of 1, you must mark a Stress to reload this weapon before you can fire it again.", 2),
  Weapon("Greatbow", "Primary", "Physical", "Strength", "Far", "d6+6 phy", "Two-Handed", "Powerful: On a successful attack, roll an additional damage die and discard the lowest result.", 2),
  Weapon("Finehair Bow", "Primary", "Physical", "Agility", "Very Far", "d6+5 phy", "Two-Handed", "Reliable: +1 to attack rolls", 2),
  Weapon("Improved Arcane Gauntlets", "Primary", "Magical", "Strength", "Melee", "d10+6 mag", "Two-Handed", ":", 2),
  Weapon("Improved Hallowed Axe", "Primary", "Magical", "Strength", "Melee", "d8+4 mag", "One-Handed", ":", 2),
  Weapon("Improved Glowing Rings", "Primary", "Magical", "Agility", "Very Close", "d10+5 mag", "Two-Handed", ":", 2),
  Weapon("Improved Hand Runes", "Primary", "Magical", "Instinct", "Very Close", "d10+3 mag", "One-Handed", ":", 2),
  Weapon("Improved Returning Blade", "Primary", "Magical", "Finesse", "Close", "d8+3 mag", "One-Handed", "Returning: When this weapon is thrown within its range, it appears in your hand immediately after the attack.", 2),
  Weapon("Improved Shortstaff", "Primary", "Magical", "Instinct", "Close", "d8+4 mag", "One-Handed", ":", 2),
  Weapon("Improved Dualstaff", "Primary", "Magical", "Instinct", "Far", "d6+6 mag", "Two-Handed", ":", 2),
  Weapon("Improved Scepter", "Primary", "Magical", "Presence", "Far", "d6+3 mag", "Two-Handed", "Versatile: This weapon can also be used with these statistics—Presence, Melee, d8+3.", 2),
  Weapon("Improved Wand", "Primary", "Magical", "Knowledge", "Far", "d6+4 mag", "One-Handed", ":", 2),
  Weapon("Improved Greatstaff", "Primary", "Magical", "Knowledge", "Very Far", "d6+3 mag", "Two-Handed", "Powerful: On a successful attack, roll an additional damage die and discard the lowest result.", 2),
  Weapon("Ego Blade", "Primary", "Magical", "Agility", "Melee", "d12+4 mag", "One-Handed", "Pompous: You must have a Presence of 0 or lower to use this weapon.", 2),
  Weapon("Casting Sword", "Primary", "Magical", "Strength", "Melee", "d10+4 mag", "Two-Handed", "Versatile: This weapon can also be used with these statistics—Knowledge, Far, d6+3.", 2),
  Weapon("Devouring Dagger", "Primary", "Magical", "Finesse", "Melee", "d8+4 mag", "One-Handed", "Scary: On a successful attack, the target must mark a Stress.", 2),
  Weapon("Hammer of Exota", "Primary", "Magical", "Instinct", "Melee", "d8+6 mag", "Two-Handed", "Eruptive: On a successful attack against a target within Melee range, all other adversaries within Very Close range must succeed on a reaction roll (14) or take half damage.", 2),
  Weapon("Yutari Bloodbow", "Primary", "Magical", "Finesse", "Far", "d6+4 mag", "Two-Handed", "Brutal: When you roll the maximum value on a damage die, roll an additional damage die.", 2),
  Weapon("Elder Bow", "Primary", "Magical", "Instinct", "Far", "d6+4 mag", "Two-Handed", "Powerful: On a successful attack, roll an additional damage die and discard the lowest result.", 2),
  Weapon("Scepter of Elias", "Primary", "Magical", "Presence", "Far", "d6+3 mag", "One-Handed", "Invigorating: On a successful attack, roll a d4. On a result of 4, clear a Stress.", 2),
  Weapon("Wand of Enthrallment", "Primary", "Magical", "Presence", "Far", "d6+4 mag", "One-Handed", "Persuasive: Before you make a Presence Roll, you can mark a Stress to gain a +2 bonus to the result.", 2),
  Weapon("Keeper’s Staff", "Primary", "Magical", "Knowledge", "Far", "d6+4 mag", "Two-Handed", "Reliable: +1 to attack rolls", 2),
  Weapon("Improved Shortsword", "Secondary", "Physical", "Agility", "Melee", "d8+2 phy", "One-Handed", "Paired: +3 to primary weapon damage to targets within Melee range", 2),
  Weapon("Improved Round Shield", "Secondary", "Physical", "Strength", "Melee", "d4+2 phy", "One-Handed", "Protective: +2 to Armor Score", 2),
  Weapon("Improved Tower Shield", "Secondary", "Physical", "Strength", "Melee", "d6+2 phy", "One-Handed", "Barrier: +3 to Armor Score; -1 to Evasion", 2),
  Weapon("Improved Small Dagger", "Secondary", "Physical", "Finesse", "Melee", "d8+2 phy", "One-Handed", "Paired: +3 to primary weapon damage to targets within Melee range", 2),
  Weapon("Improved Whip", "Secondary", "Physical", "Presence", "Very Close", "d6+2 phy", "One-Handed", "Startling: Mark a Stress to crack the whip and force all adversaries within Melee range back to Close range.", 2),
  Weapon("Improved Grappler", "Secondary", "Physical", "Finesse", "Close", "d6+2 phy", "One-Handed", "Hooked: On a successful attack, you can pull the target into Melee range.", 2),
  Weapon("Improved Hand Crossbow", "Secondary", "Physical", "Finesse", "Far", "d6+3 phy", "One-Handed", ":", 2),
  Weapon("Spiked Shield", "Secondary", "Physical", "Strength", "Melee", "d6+2 phy", "One-Handed", "Double Duty: +1 to Armor Score; +1 to primary weapon damage within Melee range", 2),
  Weapon("Parrying Dagger", "Secondary", "Physical", "Finesse", "Melee", "d6+2 phy", "One-Handed", "Parry: When you are attacked, roll this weapon’s damage dice. If any of the attacker’s damage dice rolled the same value as your dice, the matching results are discarded from the attacker’s damage dice before the damage you take is totaled.", 2),
  Weapon("Returning Axe", "Secondary", "Physical", "Agility", "Close", "d6+4 phy", "One-Handed", "Returning: When this weapon is thrown within its range, it appears in your hand immediately after the attack.", 2),
  Weapon("Advanced Broadsword", "Primary", "Physical", "Agility", "Melee", "d8+6 phy", "One-Handed", "Reliable: +1 to attack rolls", 3),
  Weapon("Advanced Longsword", "Primary", "Physical", "Agility", "Melee", "d10+9 phy", "Two-Handed", ":", 3),
  Weapon("Advanced Battleaxe", "Primary", "Physical", "Strength", "Melee", "d10+9 phy", "Two-Handed", ":", 3),
  Weapon("Advanced Greatsword", "Primary", "Physical", "Strength", "Melee", "d10+9 phy", "Two-Handed", "Massive: -1 to Evasion; on a successful attack, roll an additional damage die and discard the lowest result.", 3),
  Weapon("Advanced Mace", "Primary", "Physical", "Strength", "Melee", "d8+7 phy", "One-Handed", ":", 3),
  Weapon("Advanced Warhammer", "Primary", "Physical", "Strength", "Melee", "d12+9 phy", "Two-Handed", "Heavy: -1 to Evasion", 3),
  Weapon("Advanced Dagger", "Primary", "Physical", "Finesse", "Melee", "d8+7 phy", "One-Handed", ":", 3),
  Weapon("Advanced Quarterstaff", "Primary", "Physical", "Instinct", "Melee", "d10+9 phy", "Two-Handed", ":", 3),
  Weapon("Advanced Cutlass", "Primary", "Physical", "Presence", "Melee", "d8+7 phy", "One-Handed", ":", 3),
  Weapon("Advanced Rapier", "Primary", "Physical", "Presence", "Melee", "d8+6 phy", "One-Handed", "Quick: When you make an attack, you can mark a Stress to target another creature within range.", 3),
  Weapon("Advanced Halberd", "Primary", "Physical", "Strength", "Very Close", "d10+8 phy", "Two-Handed", "Cumbersome: -1 to Finesse", 3),
  Weapon("Advanced Spear", "Primary", "Physical", "Finesse", "Very Close", "d8+9 phy", "Two-Handed", ": -1 to Finesse", 3),
  Weapon("Advanced Shortbow", "Primary", "Physical", "Agility", "Far", "d6+9 phy", "Two-Handed", ":", 3),
  Weapon("Advanced Crossbow", "Primary", "Physical", "Finesse", "Far", "d6+7 phy", "One-Handed", ":", 3),
  Weapon("Advanced Longbow", "Primary", "Physical", "Agility", "Very Far", "d8+9 phy", "Two-Handed", "Cumbersome: -1 to Finesse", 3),
  Weapon("Flickerfly Blade", "Primary", "Physical", "Agility", "Melee", "d8+5 phy", "One-Handed", "Sharpening: Gain a bonus to your damage rolls equal to your Agility.", 3),
  Weapon("Bravesword", "Primary", "Physical", "Strength", "Melee", "d12+7 phy", "Two-Handed", "Brave: -1 to Evasion; +3 to Severe damage threshold", 3),
  Weapon("Hammer of Wrath", "Primary", "Physical", "Strength", "Melee", "d10+7 phy", "Two-Handed", "Devastating: Before you make an attack roll, you can mark a Stress to use a d20 as your damage die.", 3),
  Weapon("Labrys Axe", "Primary", "Physical", "Strength", "Melee", "d10+7 phy", "Two-Handed", "Protective: +1 to Armor Score", 3),
  Weapon("Meridian Cutlass", "Primary", "Physical", "Presence", "Melee", "d10+5 phy", "One-Handed", "Dueling: When there are no other creatures within Close range of the target, gain advantage on your attack roll against them.", 3),
  Weapon("Retractable Saber", "Primary", "Physical", "Presence", "Melee", "d10+7 phy", "One-Handed", "Retractable: The blade can be hidden in the hilt to avoid detection.", 3),
  Weapon("Double Flail", "Primary", "Physical", "Agility", "Very Close", "d10+8 phy", "Two-Handed", "Powerful: On a successful attack, roll an additional damage die and discard the lowest result.", 3),
  Weapon("Talon Blades", "Primary", "Physical", "Finesse", "Close", "d10+7 phy", "Two-Handed", "Brutal: When you roll the maximum value on a damage die, roll an additional damage die.", 3),
  Weapon("Black Powder Revolver", "Primary", "Physical", "Finesse", "Far", "d6+8 phy", "One-Handed", "Reloading: After you make an attack, roll a d6. On a result of 1, you must mark a Stress to reload this weapon before you can fire it again.", 3),
  Weapon("Spiked Bow", "Primary", "Physical", "Agility", "Very Far", "d6+7 phy", "Two-Handed", "Versatile: This weapon can also be used with these statistics—Agility, Melee, d10+5.", 3),
  Weapon("Advanced Arcane Gauntlets", "Primary", "Magical", "Strength", "Melee", "d10+9 mag", "Two-Handed", ":", 3),
  Weapon("Advanced Hallowed Axe", "Primary", "Magical", "Strength", "Melee", "d8+7 mag", "One-Handed", ":", 3),
  Weapon("Advanced Glowing Rings", "Primary", "Magical", "Agility", "Very Close", "d10+8 mag", "Two-Handed", ":", 3),
  Weapon("Advanced Hand Runes", "Primary", "Magical", "Instinct", "Very Close", "d10+6 mag", "One-Handed", ":", 3),
  Weapon("Advanced Returning Blade", "Primary", "Magical", "Finesse", "Close", "d8+6 mag", "One-Handed", "Returning: When this weapon is thrown within its range, it appears in your hand immediately after the attack.", 3),
  Weapon("Advanced Shortstaff", "Primary", "Magical", "Instinct", "Close", "d8+7 mag", "One-Handed", ":", 3),
  Weapon("Advanced Dualstaff", "Primary", "Magical", "Instinct", "Far", "d6+9 mag", "Two-Handed", ":", 3),
  Weapon("Advanced Scepter", "Primary", "Magical", "Presence", "Far", "d6+6 mag", "Two-Handed", "Versatile: This weapon can also be used with these statistics—Presence, Melee, d8+4.", 3),
  Weapon("Advanced Wand", "Primary", "Magical", "Knowledge", "Far", "d6+7 mag", "One-Handed", ":", 3),
  Weapon("Advanced Greatstaff", "Primary", "Magical", "Knowledge", "Very Far", "d6+6 mag", "Two-Handed", "Powerful: On a successful attack, roll an additional damage die and discard the lowest result.", 3),
  Weapon("Axe of Fortunis", "Primary", "Magical", "Strength", "Melee", "d10+8 mag", "Two-Handed", "Lucky: On a failed attack, you can mark a Stress to reroll your attack.", 3),
  Weapon("Blessed Anlace", "Primary", "Magical", "Instinct", "Melee", "d10+6 mag", "One-Handed", "Healing: During downtime, automatically clear a Hit Point.", 3),
  Weapon("Ghostblade", "Primary", "Physical or Magical", "Presence", "Melee", "d10+7 phy or mag", "One-Handed", "Otherworldly: On a successful attack, you can deal physical or magic damage.", 3),
  Weapon("Runes of Ruination", "Primary", "Magical", "Knowledge", "Very Close", "d20+4 mag", "One-Handed", "Painful: Each time you make a successful attack, you must mark a Stress.", 3),
  Weapon("Widgast Pendant", "Primary", "Magical", "Knowledge", "Close", "d10+5 mag", "One-Handed", "Timebending: You choose the target of your attack after making your attack roll.", 3),
  Weapon("Gilded Bow", "Primary", "Magical", "Finesse", "Far", "d6+7 mag", "Two-Handed", "Self-Correcting: When you roll a 1 on a damage die, it deals 6 damage instead.", 3),
  Weapon("Firestaff", "Primary", "Magical", "Instinct", "Far", "d6+7 mag", "Two-Handed", "Burning: When you roll a 6 on a damage die, the target must mark a Stress.", 3),
  Weapon("Mage Orb", "Primary", "Magical", "Knowledge", "Far", "d6+7 mag", "One-Handed", "Powerful: On a successful attack, roll an additional damage die and discard the lowest result.", 3),
  Weapon("Ilmari's Rifle", "Primary", "Magical", "Finesse", "Very Far", "d6+6 mag", "One-Handed", "Reloading: After you make an attack, roll a d6. On a result of 1, you must mark a Stress to reload this weapon before you can fire it again.", 3),
  Weapon("Advanced Shortsword", "Secondary", "Physical", "Agility", "Melee", "d8+4 phy", "One-Handed", "Paired: +4 to primary weapon damage to targets within Melee range", 3),
  Weapon("Advanced Round Shield", "Secondary", "Physical", "Strength", "Melee", "d4+4 phy", "One-Handed", "Protective: +3 to Armor Score", 3),
  Weapon("Advanced Tower Shield", "Secondary", "Physical", "Strength", "Melee", "d6+4 phy", "One-Handed", "Barrier: +4 to Armor Score; –1 to Evasion", 3),
  Weapon("Advanced Small Dagger", "Secondary", "Physical", "Finesse", "Melee", "d8+4 phy", "One-Handed", "Paired: +4 to primary weapon damage to targets within Melee range", 3),
  Weapon("Advanced Whip", "Secondary", "Physical", "Presence", "Very Close", "d6+4 phy", "One-Handed", "Startling: Mark a Stress to crack the whip and force all adversaries within Melee range back to Close range.", 3),
  Weapon("Advanced Grappler", "Secondary", "Physical", "Finesse", "Close", "d6+4 phy", "One-Handed", "Hooked: On a successful attack, you can pull the target into Melee range.", 3),
  Weapon("Advanced Hand Crossbow", "Secondary", "Physical", "Finesse", "Far", "d6+5 phy", "One-Handed", ":", 3),
  Weapon("Buckler", "Secondary", "Physical", "Agility", "Melee", "d4+4 phy", "One-Handed", "Deflecting: When you are attacked, you can mark an Armor Slot to gain a bonus to your Evasion equal to your available Armor Slots against the attack.", 3),
  Weapon("Powered Gauntlet", "Secondary", "Physical", "Knowledge", "Close", "d6+4 phy", "One-Handed", "Charged: Mark a Stress to gain a +1 bonus to your Proficiency on a primary weapon attack.", 3),
  Weapon("Hand Sling", "Secondary", "Physical", "Finesse", "Very Close", "d6+4 phy", "One-Handed", "Versatile: This weapon can also be used with these statistics—Finesse, Close, d8+4.", 3),
  Weapon("Legendary Broadsword", "Primary", "Physical", "Agility", "Melee", "d8+9 phy", "One-Handed", "Reliable: +1 to attack rolls", 4),
  Weapon("Legendary Longsword", "Primary", "Physical", "Agility", "Melee", "d10+12 phy", "Two-Handed", ":", 4),
  Weapon("Legendary Battleaxe", "Primary", "Physical", "Strength", "Melee", "d10+12 phy", "Two-Handed", ":", 4),
  Weapon("Legendary Greatsword", "Primary", "Physical", "Strength", "Melee", "d10+12 phy", "Two-Handed", "Massive: -1 to Evasion; on a successful attack, roll an additional damage die and discard the lowest result.", 4),
  Weapon("Legendary Mace", "Primary", "Physical", "Strength", "Melee", "d8+10 phy", "One-Handed", ":", 4),
  Weapon("Legendary Warhammer", "Primary", "Physical", "Strength", "Melee", "d12+12 phy", "Two-Handed", "Heavy: -1 to Evasion", 4),
  Weapon("Legendary Dagger", "Primary", "Physical", "Finesse", "Melee", "d8+10 phy", "One-Handed", ":", 4),
  Weapon("Legendary Quarterstaff", "Primary", "Physical", "Instinct", "Melee", "d10+12 phy", "Two-Handed", ":", 4),
  Weapon("Legendary Cutlass", "Primary", "Physical", "Presence", "Melee", "d8+10 phy", "One-Handed", ":", 4),
  Weapon("Legendary Rapier", "Primary", "Physical", "Presence", "Melee", "d8+9 phy", "One-Handed", "Quick: When you make an attack, you can mark a Stress to target another creature within range.", 4),
  Weapon("Legendary Halberd", "Primary", "Physical", "Strength", "Very Close", "d10+11 phy", "Two-Handed", "Cumbersome: -1 to Finesse", 4),
  Weapon("Legendary Spear", "Primary", "Physical", "Finesse", "Very Close", "d8+12 phy", "Two-Handed", ": -1 to Finesse", 4),
  Weapon("Legendary Shortbow", "Primary", "Physical", "Agility", "Far", "d6+12 phy", "Two-Handed", ":", 4),
  Weapon("Legendary Crossbow", "Primary", "Physical", "Finesse", "Far", "d6+10 phy", "One-Handed", ":", 4),
  Weapon("Legendary Longbow", "Primary", "Physical", "Agility", "Very Far", "d8+12 phy", "Two-Handed", "Cumbersome: -1 to Finesse", 4),
  Weapon("Dual-Ended Sword", "Primary", "Physical", "Agility", "Melee", "d10+9 phy", "Two-Handed", "Quick: When you make an attack, you can mark a Stress to target another creature within range.", 4),
  Weapon("Impact Gauntlet", "Primary", "Physical", "Strength", "Melee", "d10+11 phy", "One-Handed", "Concussive: On a successful attack, you can spend a Hope to knock the target back to Far range.", 4),
  Weapon("Sledge Axe", "Primary", "Physical", "Strength", "Melee", "d12+13 phy", "Two-Handed", "Destructive: -1 to Agility; on a successful attack, all adversaries within Very Close range must mark a Stress.", 4),
  Weapon("Curved Dagger", "Primary", "Physical", "Finesse", "Melee", "d8+9 phy", "One-Handed", "Serrated: When you roll a 1 on a damage die, it deals 8 damage instead.", 4),
  Weapon("Extended Polearm", "Primary", "Physical", "Finesse", "Very Close", "d8+10 phy", "Two-Handed", "Long: This weapon’s attack targets all adversaries in a line within range.", 4),
  Weapon("Swinging Ropeblade", "Primary", "Physical", "Presence", "Close", "d8+9 phy", "One-Handed", "Grappling: On a successful attack, you can spend a Hope to Restrain the target or pull them into Melee range with you.", 4),
  Weapon("Ricochet Axes", "Primary", "Physical", "Agility", "Far", "d6+11 phy", "Two-Handed", "Bouncing: Mark 1 or more Stress to hit that many targets in range of the attack.", 4),
  Weapon("Aantari Bow", "Primary", "Physical", "Finesse", "Far", "d6+11 phy", "Two-Handed", "Reliable: +1 to attack rolls", 4),
  Weapon("Hand Cannon", "Primary", "Physical", "Finesse", "Very Far", "d6+12 phy", "One-Handed", "Reloading: After you make an attack, roll a d6. On a 1, you must mark a Stress to reload this weapon before you can fire it again.", 4),
  Weapon("Legendary Arcane Gauntlets", "Primary", "Magical", "Strength", "Melee", "d10+12 mag", "Two-Handed", ":", 4),
  Weapon("Legendary Hallowed Axe", "Primary", "Magical", "Strength", "Melee", "d8+10 mag", "One-Handed", ":", 4),
  Weapon("Legendary Glowing Rings", "Primary", "Magical", "Agility", "Very Close", "d10+11 mag", "One-Handed", ":", 4),
  Weapon("Legendary Hand Runes", "Primary", "Magical", "Instinct", "Very Close", "d10+9 mag", "One-Handed", ":", 4),
  Weapon("Legendary Returning Blade", "Primary", "Magical", "Finesse", "Close", "d8+9 mag", "One-Handed", "Returning: When this weapon is thrown within its range, it appears in your hand immediately after the attack.", 4),
  Weapon("Legendary Shortstaff", "Primary", "Magical", "Instinct", "Close", "d8+10 mag", "One-Handed", ":", 4),
  Weapon("Legendary Dualstaff", "Primary", "Magical", "Instinct", "Far", "d8+12 mag", "Two-Handed", ":", 4),
  Weapon("Legendary Scepter", "Primary", "Magical", "Presence", "Far", "d6+9 mag", "Two-Handed", "Versatile: This weapon can also be used with these statistics—Presence, Melee, d8+6.", 4),
  Weapon("Legendary Wand", "Primary", "Magical", "Knowledge", "Far", "d6+10 mag", "One-Handed", ":", 4),
  Weapon("Legendary Greatstaff", "Primary", "Magical", "Knowledge", "Very Far", "d6+9 mag", "Two-Handed", "Powerful: On a successful attack, roll an additional damage die and discard the lowest result.", 4),
  Weapon("Sword of Light and Flame", "Primary", "Magical", "Strength", "Melee", "d10+11 mag", "Two-Handed", "Hot: This weapon cuts through solid material.", 4),
  Weapon("Siphoning Gauntlets", "Primary", "Magical", "Presence", "Melee", "d10+9 mag", "Two-Handed", "Lifestealing: On a successful attack, roll a d6. On a result of 6, clear a Hit Point or clear a Stress.", 4),
  Weapon("Midas Scythe", "Primary", "Magical", "Knowledge", "Melee", "d10+9 mag", "Two-Handed", "Greedy: Spend a handful of gold to gain a +1 bonus to your Proficiency on a damage roll.", 4),
  Weapon("Floating Bladeshards", "Primary", "Magical", "Instinct", "Close", "d8+9 mag", "One-Handed", "Powerful: On a successful attack, roll an additional damage die and discard the lowest result.", 4),
  Weapon("Bloodstaff", "Primary", "Magical", "Instinct", "Far", "d20+7 mag", "Two-Handed", "Painful: Each time you make a successful attack, you must mark a Stress.", 4),
  Weapon("Thistlebow", "Primary", "Magical", "Instinct", "Far", "d6+13 mag", "Two-Handed", "Reliable: +1 to attack rolls", 4),
  Weapon("Wand of Essek", "Primary", "Magical", "Knowledge", "Far", "d8+13 mag", "One-Handed", "Timebending: You can choose the target of your attack after making your attack roll.", 4),
  Weapon("Magus Revolver", "Primary", "Magical", "Finesse", "Very Far", "d6+13 mag", "One-Handed", "Reloading: After you make an attack, roll a d6. On a result of 1, you must mark a Stress to reload this weapon before you can fire it again.", 4),
  Weapon("Fusion Gloves", "Primary", "Magical", "Knowledge", "Very Far", "d6+9 mag", "Two-Handed", "Bonded: Gain a bonus to your damage rolls equal to your level.", 4),
  Weapon("Legendary Shortsword", "Secondary", "Physical", "Agility", "Melee", "d8+6 phy", "One-Handed", "Paired: +5 to primary weapon damage to targets within Melee range", 4),
  Weapon("Legendary Round Shield", "Secondary", "Physical", "Strength", "Melee", "d4+6 phy", "One-Handed", "Protective: +4 to Armor Score", 4),
  Weapon("Legendary Tower Shield", "Secondary", "Physical", "Strength", "Melee", "d6+6 phy", "One-Handed", "Barrier: +5 to Armor Score; –1 to Evasion.", 4),
  Weapon("Legendary Small Dagger", "Secondary", "Physical", "Finesse", "Melee", "d8+6 phy", "One-Handed", "Paired: +5 to primary weapon damage to targets within Melee range", 4),
  Weapon("Legendary Whip", "Secondary", "Physical", "Presence", "Very Close", "d6+6 phy", "One-Handed", "Startling: Mark a Stress to crack the whip and force all adversaries within Melee range back to Close range.", 4),
  Weapon("Legendary Grappler", "Secondary", "Physical", "Finesse", "Close", "d6+6 phy", "One-Handed", "Hooked: On a successful attack, you can pull the target into Melee range.", 4),
  Weapon("Legendary Hand Crossbow", "Secondary", "Physical", "Finesse", "Far", "d6+7 phy", "One-Handed", ":", 4),
  Weapon("Braveshield", "Secondary", "Physical", "Agility", "Melee", "d4+6 phy", "One-Handed", "Sheltering: When you mark an Armor Slot, it reduces damage for you and all allies within Melee range of you who took the same damage.", 4),
  Weapon("Knuckle Claws", "Secondary", "Physical", "Strength", "Melee", "d6+8 phy", "One-Handed", "Doubled Up: When you make an attack with your primary weapon, you can deal damage to another target within Melee range.", 4),
  Weapon("Primer Shard", "Secondary", "Physical", "Instinct", "Very Close", "d4 phy", "One-Handed", "Locked On: On a successful attack, your next attack against the same target with your primary weapon automatically succeeds.", 4),
]
